# Generated by Django 5.2.13 on 2026-04-26 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_decay_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
