# Generated by Django 5.2.13 on 2026-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_last_decay_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='stage',
            field=models.CharField(choices=[('egg', 'Egg'), ('baby', 'Baby'), ('teen', 'Teen'), ('adult', 'Adult')], default='egg', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
