# Generated by Django 5.2.13 on 2026-04-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_level_pet_stage_pet_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='coins',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
