# Generated by Django 5.2.13 on 2026-04-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('feed', 'Feed'), ('play', 'Play'), ('sleep', 'Sleep'), ('heal', 'Heal'), ('rename', 'Rename')], max_length=12)),
                ('detail', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pet', '-created_at'], name='pets_petact_pet_id_e6383a_idx')],
            },
        ),
    ]
