# Generated by Django 5.2.13 on 2026-04-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_petactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('mint', 'Mint'), ('lavender', 'Lavender'), ('gold', 'Gold')], default='pink', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_sick',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='petactionlog',
            name='action',
            field=models.CharField(choices=[('feed', 'Feed'), ('play', 'Play'), ('sleep', 'Sleep'), ('heal', 'Heal'), ('rename', 'Rename'), ('fetch', 'Fetch'), ('medicine', 'Medicine'), ('recolor', 'Recolor')], max_length=12),
        ),
        migrations.CreateModel(
            name='AchievementUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='pets.pet')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('pet', 'slug')},
            },
        ),
    ]
